# Generated by Django 4.1.3 on 2022-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_availability_status_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(blank=True, max_length=215),
        ),
    ]
