# Generated by Django 4.1.3 on 2022-11-20 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Name')),
                ('qualification', models.CharField(max_length=300, verbose_name='Qualification')),
                ('duties', models.CharField(max_length=500, verbose_name='Duties')),
                ('salary', models.CharField(max_length=240, verbose_name='Salary')),
                ('address', models.CharField(max_length=240, verbose_name='Adress')),
                ('country', models.CharField(max_length=240, verbose_name='Country')),
                ('city', models.CharField(max_length=240, verbose_name='City')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=240, verbose_name='Gender')),
                ('language', models.CharField(max_length=240, verbose_name='Language')),
                ('is_active', models.BooleanField(max_length=240, verbose_name='Is Active')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('deadline', models.CharField(max_length=240, verbose_name='Deadline')),
                ('experience_length', models.CharField(max_length=240, verbose_name='Experience')),
                ('experience_level', models.CharField(max_length=240, verbose_name='Experience Level')),
                ('created', models.DateField(auto_now_add=True)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
