# Generated by Django 4.1.3 on 2022-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_level',
            field=models.CharField(choices=[('Intern', 'Entern/Fellow Level'), ('Entry', 'Entry Level'), ('Junior manager', 'Junior Manager'), ('Experienced', 'Experienced Professional'), ('Mid-Level', 'Mid Level Manager'), ('Specialist', 'Specialist/Highly Skilled Professional'), ('General', 'General/Senior Manager'), ('Derector', 'Derector/Executive')], default='Intern', max_length=240),
            preserve_default=False,
        ),
    ]
