SPECIALISM = (
    ('Sales & Retail', 'Sales & Retail'),
    ('Marketing', 'Marketing'),
    ('Media', 'Media, communication & Writing'),
    ('Consumer Service', 'Consumer Service'),
    ('Art', 'Art, Fashion & Design'),
    ('Entertainment', 'Consumer Service'),
    ('IT & Programming', 'IT & Programming'),
    ('Data Science', 'Data Science'),
    ('Operation', 'Operation & General Management'),
    ('Manufacturing', 'Manufacturing'),
    ('Supply Chain', 'Supply Chain, Transport and Logistics'),
    ('Engineering-Design', 'Engineering- Design, Installations, Operations & Maintanance'),
    ('Engineering-Construction', 'Engineering, Construction & Planning'),
    ('Energy & Mining', 'Energy & Mining'),
    ('Science & Lab', 'Science & Lab Professionals'),
    ('Finance', 'Finance, Accounting & Auditing'),
    ('Banking', 'Banking & Investing Management'),
    ('Office & Admin', 'Office & Admin'),
    ('Hospitality', 'Restaurant & Hospitality'),
    ('Security', 'Security'),
    ('HR & Training', 'HR & Training'),
    ('Coaching & Motivation', 'Coaching & Motivation'),
    ('Social Science', 'Social Science, Research and Qualitative Assessors'),
    ('Agriculture', 'Agriculture, Forestry and Animal Care'),
    ('Legal', 'Legal'),
    ('Health Care', 'Health Care and Pharmacy'),
    ('Education', 'Education'),
    ('Real Estate', 'Real Estate'),
    ('Insurance', 'Insurance'),
    ('Aviation', 'Aviation, Travel & Tourism'),
    ('Government', 'Government, Government Relations, International Relations & Public Administration'),
    ('Business Executive', 'Business Executives'),
    ('Other', 'Other'),
)

SALES_RETAIL =(
    ('Sales Representative', 'Sales Representative'),
    ('Inside Sales', 'Inside Sales'),
    ('Outside Sales', 'Outside Sales'),
    ('Technical Sales', 'Technical Sales'),
    ('Sales Engineers','Sales Engineers'),
    ('Sales Management','Sales Management'),
    ('Retail Sales','Retail Sales'),
    ('Accounting Management', 'Accounting Management'),
    ('Business Development', 'Business Development'),
    ('Retail Outlet Management', 'Retail Outlet Management'),
    ('Supermarket Management', 'Supermarket Management'),
    ('Department Store Management', 'Department Store Management'),
    ('Hypermarket Management', 'Hypermarket Management')
)

MARKETING = (
    ('Merchandising','Merchandising'),
    ('Merchandisers','Merchandisers'),
    ('Brand Ambassadors','Brand Ambassadors'),
    ('Influencers', 'Influencers'),
    ('Social Media Marketers', 'Social Media Marketers'),
    ('Social Media Management', 'Social Media Marketing Management'),
    ('Digital Marketing', 'Digital Marketing'),
    ('Digital Marketing Analysts', 'Digital Marketing Analysts'),
    ('SEO/SEM', 'SEO/SEM and E-commerce'),
    ('Marketing Analyst', 'Marketing Analyst'),
    ('Content Writers', 'Content Writers'),
    ('Graphic Designers', 'Graphic Designers'),
    ('Advertising', 'Advertising'),
    ('Brand Management', 'Brand Management'),
    ('Promotions Management', 'Promotions Management'),
    ('Marketing Representatives', 'Marketing Representatives'),
    ('Cooperate Advertising', 'Cooperate Advertising Management'),
    ('Product Marketing', 'Product Marketing Managers'),
    ('Event Marketers', 'Event Marketers')
)

MEDIA_COMMUNICATION_AND_WRITING = (
    ('Content Management', 'Content Management'),
    ('Communication Specialists', 'Communication Specialists'),
    ('Communication Management', 'Communication Management'),
    ('Public Relations', 'Public Relations'),
    ('Technical writing', 'Technical writing'),
    ('Blog Writing', 'Blog Writing'),
    ('Screenwriting', 'Screenwriting'),
    ('Editing and Editors', 'Editing and Editors'),
    ('Copywriting', 'Copywriting'),
    ('Newspaper Publishing', 'Newspaper Publishing'),
    ('Magazine Publishing', 'Magazine Publishing'),
    ('Broadcast Journalism', 'Broadcast Journalism'),
    ('Photojournalism', 'Photojournalism'),
    ('Wire Services', 'Wire Services'),
    ('Book Publishing', 'Book Publishing'),
    ('Reporter/Correspondents', 'Reporter/Correspondents'),
    ('Photojournalists', 'Photojournalists'),
    ('Investigative Journalists', 'Investigative Journalists'),
    ('Editorial Cartoonists', 'Editorial Cartoonists'),
    ('Copy Editors/Proofreaders', 'Copy Editors/Proofreaders'),
    ('Publishers', 'Publishers'),
    ('Fact Checkers', 'Fact Checkers'),
    ('Producers', 'Producers'),
    ('Script Writers', 'Script Writers'),
    ('News Writers', 'News Writers'),
    ('Foreign Language specialists', 'Foreign Language specialists/Translators/Transcribers/Interpreters'),
)

CUSTOMER_SERVICE = (
    ('Call Centre Agents/Reps', 'Call Centre Agents/Reps'),
    ('Call Centre Management', 'Call Centre Management'),
    ('Customer Service Representatives', 'Customer Service Representatives'),
    ('Multilingual Customer Service', 'Multilingual Customer Service'),
    ('Client Relations', 'Client Relations'),
    ('Customer Service Management', 'Customer Service Management'),
    ('Front Desk Agents', 'Front Desk Agents'),
    ('Help Desk Agents', 'Help Desk Agents'),
    ('Hostess', 'Hostess'),
    ('Customer Success Management', 'Customer Success Management'),
)

ART_FASHION_DESIGN = (
    ('Graphic design','Graphic design'),
    ('Fashion design','Fashion design'),
    ('Art directorship','Art directorship'),
    ('Floral design','Floral design'),
    ('Sculptor','Sculptor'),
    ('Interior design','Interior design'),
    ('Cartoonist','Cartoonist'),
    ('Photography','Photography'),
    ('Illustrator','Illustrator'),
    ('Special effects artistry','Special effects artistry'),
    ('Animation','Animation'),
    ('Videography','Videography'),
    ('Web Designers','Web Designers'),
)

ENTERTAINMENT = (
    ('Film editing','Film editing'),
    ('Music composer','Music composer'),
    ('Choreography','Choreography'),
    ('Actors','Actors'),
    ('Musicians ','Musicians '),
    ('Singers','Singers'),
    ('Models','Models'),
    ('Dancers','Dancers'),
    ('Creative Directorship','Creative Directorship'),
)

IT_PROGRAMMING = (
    ('Cloud Computing Specialists', 'Cloud Computing Specialists'),
    ('Computer Network Specialists', 'Computer Network Specialists'),
    ('Computer Support Specialist', 'Computer Support Specialist'),
    ('Database Administrators', 'Database Administrators'),
    ('Information Technology Analysts', 'Information Technology Analysts'),
    ('Information Security Specialist', 'Information Security Specialist'),
    ('Software/Application Developers', 'Software/Application Developers'),
    ('Software Engineering', 'Software Engineering'),
    ('Web Developers', 'Web Developers'),
    ('ERP Developers', 'ERP Developers'),
    ('Solution Architects', 'Solution Architects'),
    ('System Administrator', 'System Administrator'),
    ('Data Engineering', 'Data Engineering'),
    ('Project Management - Technology', 'Project Management - Technology'),
)

DATA_SCIENCE = (
    ('Data analyst','Data analyst'),
    ('Business Analyst','Business Analyst'),
    ('Marketing Analyst','Marketing Analyst'),
    ('Data Architect','Data Architect'),
    ('Quantitative Analyst','Quantitative Analyst'),
    ('Statistician','Statistician'),
)

OPERATIONS_GENERAL_MANAGEMENT = (
    ('Operations Research Analysis','Operations Research Analysis'),
    ('Operations Management','Operations Management'),
    ('Operations Improvement','Operations Improvement'),
    ('Business Processes Reengineering','Business Processes Reengineering'),
    ('Resource Management','Resource Management'),
    ('Cost Management','Cost Management'),
    ('Project Management','Project Management'),
    ('Strategic Management','Strategic Management'),
)

MANUFACTURING = (
    ('Line supervision & Management','Line supervision & Management'),
    ('Manufacturing Management','Manufacturing Management'),
    ('Production Planning','Production Planning'),
    ('Production Management','Production Management'),
    ('Quality Assurance','Quality Assurance'),
    ('Quality Assurance Management','Quality Assurance Management'),
    ('Safety','Safety'),
    ('Safety, Health (OSHA) & Environment Management','Safety, Health (OSHA) & Environment Management'),
    ('Factory Management','Factory Management'),
    ('Continuous Improvement','Continuous Improvement'),
)

SUSPPLY_CHAIN_TRANSPORT_LOGISTICS= (
    ('Procurement Specialists', 'Procurement Specialists'),
    ('Buyers', 'Buyers'),
    ('Technical Sourcing Specialists', 'Technical Sourcing Specialists'),
    ('Procurement Management', 'Procurement Management'),
    ('Logistics Coordination', 'Logistics Coordination'),
    ('Supply Chain Coordination', 'Supply Chain Coordination'),
    ('Transport Planning', 'Transport Planning'),
    ('Store Keeping', 'Store Keeping'),
    ('Warehouse Clerks', 'Warehouse Clerks'),
    ('Distribution Management', 'Distribution Management'),
    ('Inventory Management', 'Inventory Management'),
    ('Routing/Scheduling', 'Routing/Scheduling'),
    ('Demand Planning', 'Demand Planning'),
    ('Supply Chain Analyst', 'Supply Chain Analyst'),
    ('Supply Chain Management', 'Supply Chain Management'),
    ('Clearing & Forwarding', 'Clearing & Forwarding'),
    ('Freight forwarding', 'Freight forwarding'),
)

ENGINEERING_DESIGN = (
    ('Water Engineer','Water Engineer'),
    ('Environmental Engineer','Environmental Engineer'),
    ('Mechanical Engineer','Mechanical Engineer'),
    ('Mechanical Engineer - Design','Mechanical Engineer - Design'),
    ('Mechanical Engineer - Installation','Mechanical Engineer - Installation'),
    ('Mechanical Engineer - Maintenance','Mechanical Engineer - Maintenance'),
    ('Mechanical Engineer - Building Services','Mechanical Engineer - Building Services'),
    ('Process Engineer','Process Engineer'),
    ('Petroleum Engineer','Petroleum Engineer'),
    ('Electrical Engineer','Electrical Engineer'),
    ('Electrical Engineer - Design ','Electrical Engineer - Design '),
    ('Electrical Engineer - Installation','Electrical Engineer - Installation'),
    ('Electrical Engineer - Maintenance','Electrical Engineer - Maintenance'),
    ('Electrical Engineer - Building Services','Electrical Engineer - Building Services'),
    ('Electronic Engineer','Electronic Engineer'),
    ('Mechatronics Engineer','Mechatronics Engineer'),
    ('Automotive Engineer - Design','Automotive Engineer - Design'),
    ('Automotive Engineer - Maintenance','Automotive Engineer - Maintenance'),
    ('Aerospace Engineer - Design','Aerospace Engineer - Design'),
    ('Aerospace Engineer - Maintenance','Aerospace Engineer - Maintenance'),
    ('Project Management - Design & Installations','Project Management - Design & Installations'),
)

ENGINEERING_CONSTRUCTION_PLANNING = (
    ('Civil Engineer', 'Civil Engineer'),
    ('Structural Engineer', 'Structural Engineer'),
    ('Geotechnical Engineer', 'Geotechnical Engineer'),
    ('Construction Manager', 'Construction Manager'),
    ('Quantity Survey', 'Quantity Survey'),
    ('Land Survey', 'Land Survey'),
    ('Construction management', 'Construction management'),
    ('Architecture', 'Architecture'),
    ('Landscape architecture', 'Landscape architecture'),
    ('Town planning', 'Town planning'),
    ('Drafting', 'Drafting'),
    ('GIS', 'GIS'),
    ('Construction inspector', 'Construction inspector'),
    ('Cost estimator', 'Cost estimator'),
    ('Construction Safety Management', 'Construction Safety Management'),
    ('Project Manager - Engineering & Construction', 'Project Manager - Engineering & Construction'),
)

ENERGY_MINING = (
    ('Geological Engineer','Geological Engineer'),
    ('Geoscientist','Geoscientist'),
    ('Nuclear Engineers','Nuclear Engineers'),
    ('Mining Engineer','Mining Engineer'),
    ('Mine Safety Engineer','Mine Safety Engineer'),
    ('Mine Safety Management','Mine Safety Management'),
    ('Mineral and Rock Research and Science','Mineral and Rock Research and Science'),
    ('Mining Consultant','Mining Consultant'),
    ('Open Pit Mining Management','Open Pit Mining Management'),
    ('Planning Engineer (Surface and Underground)','Planning Engineer (Surface and Underground)'),
    ('Process Mining Digital Engineer','Process Mining Digital Engineer'),
    ('Project Engineer','Project Engineer'),
    ('Tech Specialist Mining Systems','Tech Specialist Mining Systems'),
    ('Underground Mining Commissioning Specialist','Underground Mining Commissioning Specialist'),
    ('Surface Mining Supervision','Surface Mining Supervision'),
)

SCIENCE_LAB_PROFESSIONALS=(
    ('Analytical chemist','Analytical chemist'),
    ('Animal technician','Animal technician'),
    ('Biomedical engineer','Biomedical engineer'),
    ('Biomedical scientist','Biomedical scientist'),
    ('Clinical psychologist','Clinical psychologist'),
    ('Forensic scientist','Forensic scientist'),
    ('Medicinal chemist','Medicinal chemist'),
    ('Metallurgist','Metallurgist'),
    ('Plant breeder/geneticist','Plant breeder/geneticist'),
    ('Product/process development scientist','Product/process development scientist'),
    ('Research scientist ','Research scientist '),
    ('Scientific laboratory technician ','Scientific laboratory technician '),
    ('Toxicologist ','Toxicologist '),
    ('Water quality scientist ','Water quality scientist '),
    ('Blood Bank Specialists','Blood Bank Specialists'),
    ('Chemistry Technician','Chemistry Technician'),
    ('Hematologist','Hematologist'),
    ('Microbiologist','Microbiologist'),
    ('Molecular Diagnostics Specialist','Molecular Diagnostics Specialist'),
    ('Cytologist','Cytologist'),
    ('Histologist','Histologist'),
    ('Pathologist','Pathologist'),
    ('Lab Management','Lab Management'),
)

FINANCE_ACCOUNTING_AUDITING = (
    ('Cost Estimator','Cost Estimator'),
    ('Forensic Accountant','Forensic Accountant'),
    ('Real Estate Appraiser','Real Estate Appraiser'),
    ('Tax Accountant','Tax Accountant'),
    ('Accounting Clerk','Accounting Clerk'),
    ('Accounts Payable/Receivable Clerk','Accounts Payable/Receivable Clerk'),
    ('Accounting Information System Specialist','Accounting Information System Specialist'),
    ('Actuarial Accountant/Insurance Accountant','Actuarial Accountant/Insurance Accountant'),
    ('Bookkeeping','Bookkeeping'),
    ('Budget Analyst','Budget Analyst'),
    ('Capital Accountant','Capital Accountant'),
    ('Comptroller/Financial Controller','Comptroller/Financial Controller'),
    ('Cost Accountant','Cost Accountant'),
    ('Environmental Accountant/Sustainability Measurement','Environmental Accountant/Sustainability Measurement'),
    ('Payroll Accountant','Payroll Accountant'),
    ('Business Valuation Analyst','Business Valuation Analyst'),
    ('Certified Financial Planner','Certified Financial Planner'),
    ('Financial Analyst','Financial Analyst'),
    ('Tax Consultant','Tax Consultant'),
    ('Business Analyst','Business Analyst'),
    ('Investment Analyst ','Investment Analyst '),
    ('Internal Auditor ','Internal Auditor '),
    ('External Auditor','External Auditor'),
    ('Tax Auditor','Tax Auditor'),
    ('Forensic Auditor','Forensic Auditor'),
    ('Life actuary','Life actuary'),
    ('General Insurance Actuary','General Insurance Actuary'),
    ('Treasury','Treasury'),  
)

BANKING_INVESTMENT_MANAGEMENT=(
    ('Bank  Teller','Bank  Teller'),
    ('Bank Marketing','Bank Marketing'),
    ('Branch Management','Branch Management'),
    ('Financial Analyst','Financial Analyst'),
    ('Personal Banker','Personal Banker'),
    ('Loan Officer','Loan Officer'),
    ('Credit Analyst','Credit Analyst'),
    ('Credit Administration','Credit Administration'),
    ('Debt Recovery','Debt Recovery'),
    ('Relationship Management','Relationship Management'),
    ('Asset Management','Asset Management'),
    ('Equities Trading','Equities Trading'),
    ('Fixed Income Analyst','Fixed Income Analyst'),
    ('Foreign Exchange Trader','Foreign Exchange Trader'),
    ('Wealth Management','Wealth Management'),
    ('Equity Analyst','Equity Analyst'),
    ('Investment Banker','Investment Banker'),
    ('Portfolio Management','Portfolio Management'),
    ('Internal Auditors','Internal Auditors'),
    ('Audit Management','Audit Management'),
    ('Compliance - Banking','Compliance - Banking'),
)

OFFICE_ADMIN = (
    ('Office Administration','Office Administration'),
    ('Executive assistant','Executive assistant'),
    ('Office assistant','Office assistant'),
    ('Receptionist','Receptionist'),
    ('Office management','Office management'),
    ('Cashier','Cashier'),
    ('Data Entry Clerk','Data Entry Clerk'),
    ('Junior Clerk','Junior Clerk'),
    ('Senior Clerk','Senior Clerk'),
    ('General Clerk','General Clerk'),
)

RESTAURANT_HOSPITALITY = (
    ('Dietitian','Dietitian'),
    ('Sous Chef','Sous Chef'),
    ('Head Chef','Head Chef'),
    ('Executive Chef','Executive Chef'),
    ('Restaurant Management','Restaurant Management'),
    ('Event Planning','Event Planning'),
)


