# Generated by Django 4.1.3 on 2022-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_specialism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='art_fashion_and_design',
            field=models.CharField(choices=[('Graphic design', 'Graphic design'), ('Fashion design', 'Fashion design'), ('Art directorship', 'Art directorship'), ('Floral design', 'Floral design'), ('Sculptor', 'Sculptor'), ('Interior design', 'Interior design'), ('Cartoonist', 'Cartoonist'), ('Photography', 'Photography'), ('Illustrator', 'Illustrator'), ('Special effects artistry', 'Special effects artistry'), ('Animation', 'Animation'), ('Videography', 'Videography'), ('Web Designers', 'Web Designers')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='banking_investment_management',
            field=models.CharField(choices=[('Bank  Teller', 'Bank  Teller'), ('Bank Marketing', 'Bank Marketing'), ('Branch Management', 'Branch Management'), ('Financial Analyst', 'Financial Analyst'), ('Personal Banker', 'Personal Banker'), ('Loan Officer', 'Loan Officer'), ('Credit Analyst', 'Credit Analyst'), ('Credit Administration', 'Credit Administration'), ('Debt Recovery', 'Debt Recovery'), ('Relationship Management', 'Relationship Management'), ('Asset Management', 'Asset Management'), ('Equities Trading', 'Equities Trading'), ('Fixed Income Analyst', 'Fixed Income Analyst'), ('Foreign Exchange Trader', 'Foreign Exchange Trader'), ('Wealth Management', 'Wealth Management'), ('Equity Analyst', 'Equity Analyst'), ('Investment Banker', 'Investment Banker'), ('Portfolio Management', 'Portfolio Management'), ('Internal Auditors', 'Internal Auditors'), ('Audit Management', 'Audit Management'), ('Compliance - Banking', 'Compliance - Banking')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='customer_service',
            field=models.CharField(choices=[('Call Centre Agents/Reps', 'Call Centre Agents/Reps'), ('Call Centre Management', 'Call Centre Management'), ('Customer Service Representatives', 'Customer Service Representatives'), ('Multilingual Customer Service', 'Multilingual Customer Service'), ('Client Relations', 'Client Relations'), ('Customer Service Management', 'Customer Service Management'), ('Front Desk Agents', 'Front Desk Agents'), ('Help Desk Agents', 'Help Desk Agents'), ('Hostess', 'Hostess'), ('Customer Success Management', 'Customer Success Management')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='energy_mining',
            field=models.CharField(choices=[('Geological Engineer', 'Geological Engineer'), ('Geoscientist', 'Geoscientist'), ('Nuclear Engineers', 'Nuclear Engineers'), ('Mining Engineer', 'Mining Engineer'), ('Mine Safety Engineer', 'Mine Safety Engineer'), ('Mine Safety Management', 'Mine Safety Management'), ('Mineral and Rock Research and Science', 'Mineral and Rock Research and Science'), ('Mining Consultant', 'Mining Consultant'), ('Open Pit Mining Management', 'Open Pit Mining Management'), ('Planning Engineer (Surface and Underground)', 'Planning Engineer (Surface and Underground)'), ('Process Mining Digital Engineer', 'Process Mining Digital Engineer'), ('Project Engineer', 'Project Engineer'), ('Tech Specialist Mining Systems', 'Tech Specialist Mining Systems'), ('Underground Mining Commissioning Specialist', 'Underground Mining Commissioning Specialist'), ('Surface Mining Supervision', 'Surface Mining Supervision')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='engineering_construction_planning',
            field=models.CharField(choices=[('Civil Engineer', 'Civil Engineer'), ('Structural Engineer', 'Structural Engineer'), ('Geotechnical Engineer', 'Geotechnical Engineer'), ('Construction Manager', 'Construction Manager'), ('Quantity Survey', 'Quantity Survey'), ('Land Survey', 'Land Survey'), ('Construction management', 'Construction management'), ('Architecture', 'Architecture'), ('Landscape architecture', 'Landscape architecture'), ('Town planning', 'Town planning'), ('Drafting', 'Drafting'), ('GIS', 'GIS'), ('Construction inspector', 'Construction inspector'), ('Cost estimator', 'Cost estimator'), ('Construction Safety Management', 'Construction Safety Management'), ('Project Manager - Engineering & Construction', 'Project Manager - Engineering & Construction')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='engineering_design',
            field=models.CharField(choices=[('Water Engineer', 'Water Engineer'), ('Environmental Engineer', 'Environmental Engineer'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Mechanical Engineer - Design', 'Mechanical Engineer - Design'), ('Mechanical Engineer - Installation', 'Mechanical Engineer - Installation'), ('Mechanical Engineer - Maintenance', 'Mechanical Engineer - Maintenance'), ('Mechanical Engineer - Building Services', 'Mechanical Engineer - Building Services'), ('Process Engineer', 'Process Engineer'), ('Petroleum Engineer', 'Petroleum Engineer'), ('Electrical Engineer', 'Electrical Engineer'), ('Electrical Engineer - Design ', 'Electrical Engineer - Design '), ('Electrical Engineer - Installation', 'Electrical Engineer - Installation'), ('Electrical Engineer - Maintenance', 'Electrical Engineer - Maintenance'), ('Electrical Engineer - Building Services', 'Electrical Engineer - Building Services'), ('Electronic Engineer', 'Electronic Engineer'), ('Mechatronics Engineer', 'Mechatronics Engineer'), ('Automotive Engineer - Design', 'Automotive Engineer - Design'), ('Automotive Engineer - Maintenance', 'Automotive Engineer - Maintenance'), ('Aerospace Engineer - Design', 'Aerospace Engineer - Design'), ('Aerospace Engineer - Maintenance', 'Aerospace Engineer - Maintenance'), ('Project Management - Design & Installations', 'Project Management - Design & Installations')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='entertainment',
            field=models.CharField(choices=[('Film editing', 'Film editing'), ('Music composer', 'Music composer'), ('Choreography', 'Choreography'), ('Actors', 'Actors'), ('Musicians ', 'Musicians '), ('Singers', 'Singers'), ('Models', 'Models'), ('Dancers', 'Dancers'), ('Creative Directorship', 'Creative Directorship')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='finance_accounting_auditing',
            field=models.CharField(choices=[('Analytical chemist', 'Analytical chemist'), ('Animal technician', 'Animal technician'), ('Biomedical engineer', 'Biomedical engineer'), ('Biomedical scientist', 'Biomedical scientist'), ('Clinical psychologist', 'Clinical psychologist'), ('Forensic scientist', 'Forensic scientist'), ('Medicinal chemist', 'Medicinal chemist'), ('Metallurgist', 'Metallurgist'), ('Plant breeder/geneticist', 'Plant breeder/geneticist'), ('Product/process development scientist', 'Product/process development scientist'), ('Research scientist ', 'Research scientist '), ('Scientific laboratory technician ', 'Scientific laboratory technician '), ('Toxicologist ', 'Toxicologist '), ('Water quality scientist ', 'Water quality scientist '), ('Blood Bank Specialists', 'Blood Bank Specialists'), ('Chemistry Technician', 'Chemistry Technician'), ('Hematologist', 'Hematologist'), ('Microbiologist', 'Microbiologist'), ('Molecular Diagnostics Specialist', 'Molecular Diagnostics Specialist'), ('Cytologist', 'Cytologist'), ('Histologist', 'Histologist'), ('Pathologist', 'Pathologist'), ('Lab Management', 'Lab Management')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='it_programming',
            field=models.CharField(choices=[('Cloud Computing Specialists', 'Cloud Computing Specialists'), ('Computer Network Specialists', 'Computer Network Specialists'), ('Computer Support Specialist', 'Computer Support Specialist'), ('Database Administrators', 'Database Administrators'), ('Information Technology Analysts', 'Information Technology Analysts'), ('Information Security Specialist', 'Information Security Specialist'), ('Software/Application Developers', 'Software/Application Developers'), ('Software Engineering', 'Software Engineering'), ('Web Developers', 'Web Developers'), ('ERP Developers', 'ERP Developers'), ('Solution Architects', 'Solution Architects'), ('System Administrator', 'System Administrator'), ('Data Engineering', 'Data Engineering'), ('Project Management - Technology', 'Project Management - Technology')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manufacturing',
            field=models.CharField(choices=[('Line supervision & Management', 'Line supervision & Management'), ('Manufacturing Management', 'Manufacturing Management'), ('Production Planning', 'Production Planning'), ('Production Management', 'Production Management'), ('Quality Assurance', 'Quality Assurance'), ('Quality Assurance Management', 'Quality Assurance Management'), ('Safety', 'Safety'), ('Safety, Health (OSHA) & Environment Management', 'Safety, Health (OSHA) & Environment Management'), ('Factory Management', 'Factory Management'), ('Continuous Improvement', 'Continuous Improvement')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='marketing',
            field=models.CharField(choices=[('Merchandising', 'Merchandising'), ('Merchandisers', 'Merchandisers'), ('Brand Ambassadors', 'Brand Ambassadors'), ('Influencers', 'Influencers'), ('Social Media Marketers', 'Social Media Marketers'), ('Social Media Management', 'Social Media Marketing Management'), ('Digital Marketing', 'Digital Marketing'), ('Digital Marketing Analysts', 'Digital Marketing Analysts'), ('SEO/SEM', 'SEO/SEM and E-commerce'), ('Marketing Analyst', 'Marketing Analyst'), ('Content Writers', 'Content Writers'), ('Graphic Designers', 'Graphic Designers'), ('Advertising', 'Advertising'), ('Brand Management', 'Brand Management'), ('Promotions Management', 'Promotions Management'), ('Marketing Representatives', 'Marketing Representatives'), ('Cooperate Advertising', 'Cooperate Advertising Management'), ('Product Marketing', 'Product Marketing Managers'), ('Event Marketers', 'Event Marketers')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='media_communication',
            field=models.CharField(choices=[('Content Management', 'Content Management'), ('Communication Specialists', 'Communication Specialists'), ('Communication Management', 'Communication Management'), ('Public Relations', 'Public Relations'), ('Technical writing', 'Technical writing'), ('Blog Writing', 'Blog Writing'), ('Screenwriting', 'Screenwriting'), ('Editing and Editors', 'Editing and Editors'), ('Copywriting', 'Copywriting'), ('Newspaper Publishing', 'Newspaper Publishing'), ('Magazine Publishing', 'Magazine Publishing'), ('Broadcast Journalism', 'Broadcast Journalism'), ('Photojournalism', 'Photojournalism'), ('Wire Services', 'Wire Services'), ('Book Publishing', 'Book Publishing'), ('Reporter/Correspondents', 'Reporter/Correspondents'), ('Photojournalists', 'Photojournalists'), ('Investigative Journalists', 'Investigative Journalists'), ('Editorial Cartoonists', 'Editorial Cartoonists'), ('Copy Editors/Proofreaders', 'Copy Editors/Proofreaders'), ('Publishers', 'Publishers'), ('Fact Checkers', 'Fact Checkers'), ('Producers', 'Producers'), ('Script Writers', 'Script Writers'), ('News Writers', 'News Writers'), ('Foreign Language specialists', 'Foreign Language specialists/Translators/Transcribers/Interpreters')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='office_admin',
            field=models.CharField(choices=[('Office Administration', 'Office Administration'), ('Executive assistant', 'Executive assistant'), ('Office assistant', 'Office assistant'), ('Receptionist', 'Receptionist'), ('Office management', 'Office management'), ('Cashier', 'Cashier'), ('Data Entry Clerk', 'Data Entry Clerk'), ('Junior Clerk', 'Junior Clerk'), ('Senior Clerk', 'Senior Clerk'), ('General Clerk', 'General Clerk')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='restaurant_hospitality',
            field=models.CharField(choices=[('Dietitian', 'Dietitian'), ('Sous Chef', 'Sous Chef'), ('Head Chef', 'Head Chef'), ('Executive Chef', 'Executive Chef'), ('Restaurant Management', 'Restaurant Management'), ('Event Planning', 'Event Planning')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='sales_retail',
            field=models.CharField(choices=[('Sales Representative', 'Sales Representative'), ('Inside Sales', 'Inside Sales'), ('Outside Sales', 'Outside Sales'), ('Technical Sales', 'Technical Sales'), ('Sales Engineers', 'Sales Engineers'), ('Sales Management', 'Sales Management'), ('Retail Sales', 'Retail Sales'), ('Accounting Management', 'Accounting Management'), ('Business Development', 'Business Development'), ('Retail Outlet Management', 'Retail Outlet Management'), ('Supermarket Management', 'Supermarket Management'), ('Department Store Management', 'Department Store Management'), ('Hypermarket Management', 'Hypermarket Management')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='science_lab_professionals',
            field=models.CharField(choices=[('Analytical chemist', 'Analytical chemist'), ('Animal technician', 'Animal technician'), ('Biomedical engineer', 'Biomedical engineer'), ('Biomedical scientist', 'Biomedical scientist'), ('Clinical psychologist', 'Clinical psychologist'), ('Forensic scientist', 'Forensic scientist'), ('Medicinal chemist', 'Medicinal chemist'), ('Metallurgist', 'Metallurgist'), ('Plant breeder/geneticist', 'Plant breeder/geneticist'), ('Product/process development scientist', 'Product/process development scientist'), ('Research scientist ', 'Research scientist '), ('Scientific laboratory technician ', 'Scientific laboratory technician '), ('Toxicologist ', 'Toxicologist '), ('Water quality scientist ', 'Water quality scientist '), ('Blood Bank Specialists', 'Blood Bank Specialists'), ('Chemistry Technician', 'Chemistry Technician'), ('Hematologist', 'Hematologist'), ('Microbiologist', 'Microbiologist'), ('Molecular Diagnostics Specialist', 'Molecular Diagnostics Specialist'), ('Cytologist', 'Cytologist'), ('Histologist', 'Histologist'), ('Pathologist', 'Pathologist'), ('Lab Management', 'Lab Management')], max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='supply_chain_transport_logistics',
            field=models.CharField(choices=[('Procurement Specialists', 'Procurement Specialists'), ('Buyers', 'Buyers'), ('Technical Sourcing Specialists', 'Technical Sourcing Specialists'), ('Procurement Management', 'Procurement Management'), ('Logistics Coordination', 'Logistics Coordination'), ('Supply Chain Coordination', 'Supply Chain Coordination'), ('Transport Planning', 'Transport Planning'), ('Store Keeping', 'Store Keeping'), ('Warehouse Clerks', 'Warehouse Clerks'), ('Distribution Management', 'Distribution Management'), ('Inventory Management', 'Inventory Management'), ('Routing/Scheduling', 'Routing/Scheduling'), ('Demand Planning', 'Demand Planning'), ('Supply Chain Analyst', 'Supply Chain Analyst'), ('Supply Chain Management', 'Supply Chain Management'), ('Clearing & Forwarding', 'Clearing & Forwarding'), ('Freight forwarding', 'Freight forwarding')], max_length=240, null=True),
        ),
    ]
